-- Sales Data Exploratory Data Analysis

-- 1. Database Exploration
-- Exploring All Objects in the Database
SELECT  * 
FROM INFORMATION_SCHEMA.TABLES;

-- Exploring All Columns in the Database
SELECT  * 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';

-- 2. Dimension Exploration
-- Exploring All Countries From Our Customers Come From 
SELECT DISTINCT country 
FROM dim_customers;

-- Exploring All Categories "The major Divisions"
SELECT DISTINCT category 
FROM dim_products
ORDER BY 1; 

SELECT DISTINCT category, subcategory 
FROM dim_products
ORDER BY 1,2; 

SELECT DISTINCT category, subcategory, product_name
FROM dim_products
ORDER BY 1,2,3;

-- 3. Date Exploration
-- Finding the date of first and last order
-- Finding the years of sales
SELECT order_date 
FROM fact_sales;

SELECT 
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	YEAR(MAX(order_date)) -  YEAR(MIN(order_date))  AS order_range_years
FROM fact_sales;

-- Finding youngest and oldest customer
SELECT 
	MIN(birthdate) AS oldest_birthdate,
	MAX(birthdate) AS youngest_birthdate
FROM dim_customers;

SELECT 
    TIMESTAMPDIFF(YEAR, MIN(birthdate), CURRENT_DATE()) AS oldest_customer_age,
    TIMESTAMPDIFF(YEAR, MAX(birthdate), CURRENT_DATE()) AS youngest_customer_age
FROM dim_customers;

-- 4. Measures Exploration
-- Finding the total sales
SELECT SUM(sales_amount) AS total_sales
FROM fact_sales;

-- Finding how many items sold
SELECT SUM(quantity) AS total_quantity
FROM fact_sales;

-- Finding the average selling price
SELECT AVG(price) AS avg_price
FROM fact_sales;

-- Finding the total number of orders
SELECT COUNT(order_number) AS total_orders
FROM fact_sales;

SELECT COUNT(DISTINCT order_number) AS total_orders
FROM fact_sales;

-- Finding the total number of products
SELECT COUNT(product_name) AS total_products
FROM dim_products;

SELECT COUNT(DISTINCT product_name) AS total_products
FROM dim_products;

-- Finding the total number of customers
SELECT COUNT(customer_key) AS total_customers
FROM dim_customers;

SELECT COUNT(DISTINCT customer_key) AS total_customers
FROM dim_customers;

-- Finding the total number of customers that has placed an order
-- SELECT COUNT(DISTINCT c.customer_key) AS total_customers
-- FROM dim_customers AS c
-- JOIN fact_sales AS s
-- ON c.customer_key = s.customer_key;

SELECT COUNT(DISTINCT customer_key) AS total_customers
FROM fact_sales; 

-- Generating a report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name,
	SUM(sales_amount) AS measure_value
FROM fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name,
	SUM(quantity) AS measure_value
FROM fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name,
	AVG(price) AS measure_value
FROM fact_sales
UNION ALL
SELECT 'Total Order' AS measur_name,
	COUNT(DISTINCT order_number) AS measure_value
FROM fact_sales
UNION ALL
SELECT 'Total Products' AS measure_name,
	COUNT(product_name) AS measure_value
FROM dim_products
UNION ALL
SELECT 'Total Customers' AS measure_name,
	COUNT(customer_key) AS total_customers
FROM dim_customers;

-- 5. Magnitude Analysis
-- FInding total customers by countries
SELECT country,
	COUNT(DISTINCT customer_key) AS total_customers
FROM dim_customers
GROUP BY 1
ORDER BY 2 DESC;

-- Finding total customers by gender 
SELECT gender,
	COUNT(DISTINCT customer_key) AS total_customers
FROM dim_customers
GROUP BY 1
ORDER BY 2 DESC;
 
 -- Finding total products by cattegories
SELECT category,
	COUNT(product_name) AS total_products
FROM dim_products
GROUP BY 1
ORDER BY 2 DESC;
 
 -- What is the average costs in each categoty?
SELECT category,
	AVG(cost) AS avg_cost
FROM dim_products
GROUP BY 1
ORDER BY 2 DESC;
 
 -- What is the total revenue generated for each category?
 SELECT p.category, 
	SUM(sales_amount) AS total_revenue
 FROM dim_products AS p
 LEFT JOIN fact_sales AS s
 ON p.product_key = s.product_key
 GROUP BY 1
 ORDER BY 2 DESC;
 
 -- Finding the total revenue generated by each customer
 SELECT c.customer_key,
	c.first_name, 
    c.last_name, 
	SUM(s.sales_amount) AS total_revenue
 FROM dim_customers AS c
 LEFT JOIN fact_sales AS s
 ON c.customer_key = s.customer_key
 GROUP BY 1,2,3
 ORDER BY 4 DESC;
 
 -- What is the distribution of sold items across countries?
SELECT c.country, SUM(s.quantity) as total_sold_items
FROM dim_customers AS c
LEFT JOIN fact_sales AS s
ON c.customer_key = s.customer_key
GROUP BY 1
ORDER BY 2 DESC;

-- 6. Ranking Analysis
-- Which 5 products generate the highest revenue?
SELECT p.product_name,
	SUM(s.sales_amount) AS total_revenue
FROM dim_products AS p
LEFT JOIN fact_sales AS s
ON p.product_key = s.product_key
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

SELECT p.product_name,
	SUM(s.sales_amount) AS total_revenue,
    ROW_NUMBER() OVER(ORDER BY SUM(s.sales_amount) DESC) as rank_products
FROM dim_products AS p
LEFT JOIN fact_sales AS s
ON p.product_key = s.product_key
GROUP BY 1
LIMIT 5;

WITH RankedProducts AS (
SELECT p.product_name,
	SUM(s.sales_amount) AS total_revenue,
    ROW_NUMBER() OVER(ORDER BY SUM(s.sales_amount) DESC) as rank_products
FROM dim_products AS p
LEFT JOIN fact_sales AS s
ON p.product_key = s.product_key
GROUP BY 1)
SELECT *
FROM RankedProducts
WHERE rank_products <= 5;


-- Which 5 subcategories generate the highest revenue?
SELECT p.subcategory,
	SUM(s.sales_amount) AS total_revenue
FROM dim_products AS p
LEFT JOIN fact_sales AS s
ON p.product_key = s.product_key
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

-- What are the 5 worst performing products in term of sales?
SELECT p.product_name,
	SUM(s.sales_amount) AS total_revenue
FROM dim_products AS p
LEFT JOIN fact_sales AS s
ON p.product_key = s.product_key
WHERE s.sales_amount IS NOT NULL
GROUP BY 1
ORDER BY 2 
LIMIT 5;

-- Finding the top 10 customers who generated the highest revenue
SELECT *
FROM (
SELECT c.customer_key, 
	c.first_name, 
    c.last_name, 
    SUM(s.sales_amount), 
    DENSE_RANK() OVER(ORDER BY SUM(s.sales_amount) DESC) AS rank_customers
FROM dim_customers AS c
LEFT JOIN fact_sales AS s
ON c.customer_key = s.customer_key
GROUP BY 1,2,3) AS RankedCustomers
WHERE rank_customers <= 10;

-- The 3 customers with the fewest orders placed
WITH RankedOrders AS (
SELECT c.customer_key, 
	c.first_name, 
    c.last_name,
    COUNT(distinct s.order_number) AS total_orders,
    DENSE_RANK() OVER (ORDER BY COUNT(distinct s.order_number)) AS rank_orders
FROM dim_customers AS c
INNER JOIN fact_sales AS s
ON c.customer_key = s.customer_key
GROUP BY 1,2,3) 
SELECT *
FROM RankedOrders
limit 3;












